name: sciqlop
channels:
  - conda-forge
dependencies:
  - python<3.11
  - pip
  
  - numpy
  - ipykernel
  
  - qasync
  - pip:
    - PySide6-QtAds==4.1.0.3
    - PySide6==6.6.1
    - SciQLopPlots>=0.6.1
    - .