name: SingleExe

on:
  release:
    types: [ published ]
  push:
  pull_request:


jobs:
  build_appimage:
    runs-on: ubuntu-latest
    container:
      image: fedora:39
    steps:
      - uses: actions/checkout@v3
      - name: bundle SciQLop
        run: |
          dnf update -y && dnf install -y wget file
          sh ./appimage/build.sh
      - name: Save packages as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SciQLop-x86_64.AppImage
          path: dist/SciQLop-x86_64.AppImage

  Publish:
    runs-on: ubuntu-latest
    needs: build_appimage
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: SciQLop-x86_64.AppImage
          path: dist
      - name: Publish to GitHub Releases
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv dist/SciQLop-x86_64.AppImage dist/SciQLop-x86_64-${{ github.event.release.tag_name }}.AppImage
          gh release upload ${{ github.event.release.tag_name }} dist/SciQLop-x86_64-${{ github.event.release.tag_name }}.AppImage
